CREATE TABLE t_part1
PARTITION BY HASH (c1)
   PARTITIONS 8
AS
   SELECT c1, ROWNUM AS c3 FROM t1;

CREATE TABLE t_part2
PARTITION BY HASH (c2)
   PARTITIONS 8
AS
   SELECT c1 AS c2, ROWNUM AS c4 FROM t1;

ALTER SESSION ENABLE PARALLEL DML;

EXPLAIN PLAN
   FOR
      INSERT /*+ parallel(t_part1 8) pq_distribute(t_part1 PARTITION) */
            INTO  t_part1
         SELECT c1, c1 FROM t1;

SET LINES 200 PAGES 0

SELECT * FROM TABLE (DBMS_XPLAN.display);