CREATE PUBLIC DATABASE LINK "loopback"
USING 'localhost:1521/orcl'; -- Customize for your database name and port

CREATE /*+ NO_GATHER_OPTIMIZER_STATISTICS */ TABLE t1 AS
SELECT ROWNUM c1 FROM DUAL CONNECT BY LEVEL <= 100;
CREATE /*+ NO_GATHER_OPTIMIZER_STATISTICS */ TABLE t2 AS
SELECT ROWNUM c2 FROM DUAL CONNECT BY LEVEL <= 100;
CREATE /*+ NO_GATHER_OPTIMIZER_STATISTICS */ TABLE t3 AS
SELECT ROWNUM c3 FROM DUAL CONNECT BY LEVEL <= 100;
CREATE /*+ NO_GATHER_OPTIMIZER_STATISTICS */ TABLE t4 AS
SELECT ROWNUM c4 FROM DUAL CONNECT BY LEVEL <= 100;
